### ISSUE TITLE
DroppedSpan causing AttributeError

### ISSUE THREAD

**Issue by HonzaKral** [elastic/apm-agent-python#1169]
**Describe the bug**: celery tasks are now failing with attribute errors caused by APM

**Environment (please complete the following information)**
- OS: Linux
- Python version: 3.8.5
- Framework and version [e.g. Django 2.1]: Django 3.2.3, Celery 5.0.5
- APM Server version: 7.13
- Agent version: 6.2.2

Could be related to #468

Traceback:
```
Traceback (most recent call last):
......
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/celery/app/task.py", line 421, in delay
return self.apply_async(args, kwargs)
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/celery/app/task.py", line 561, in apply_async
return app.send_task(
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/celery/app/base.py", line 749, in send_task
amqp.send_task_message(P, name, message, **options)
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/celery/app/amqp.py", line 523, in send_task_message
ret = producer.publish(
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/kombu/messaging.py", line 175, in publish
return _publish(
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/kombu/connection.py", line 525, in _ensured
return fun(*args, **kwargs)
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/kombu/messaging.py", line 197, in _publish
return channel.basic_publish(
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 605, in basic_publish
return self._put(routing_key, message, **kwargs)
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/kombu/transport/SQS.py", line 294, in _put
c.send_message(**kwargs)
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/elasticapm/instrumentation/packages/base.py", line 210, in call_if_sampling
return self.call(module, method, wrapped, instance, args, kwargs)
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/elasticapm/instrumentation/packages/botocore.py", line 91, in call
span_modifiers[service](span, args, kwargs)
File "/aimful/shared/virtualenv/lib/python3.8/site-packages/elasticapm/instrumentation/packages/botocore.py", line 174, in modify_span_sqs
trace_parent = span.transaction.trace_parent.copy_from(span_id=span.id)
AttributeError: 'DroppedSpan' object has no attribute 'transaction'
```

**Comment by beniwohli** [comment]
Hey @HonzaKral! Great catch, I opened #1170 with a fix (and took the opportunity to also close some gaps in testing the SQS instrumentation).
