### ISSUE TITLE
httpx instrumentation: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Tayum** [elastic/apm-agent-python#1336]
**Describe the bug**
In some cases `httpx` passes `request` param to its `httpx.Client.send()` as keyword argument rather than positional one, like e.g. when using `httpx.Client.stream()` in a context manager, which is unacceptable by `elastic-apm`.
**Please note same happens when using `httpx.AsyncClient.stream()` instead of sync `httpx.Client.stream()`**.

**Current workaround**
Disable `httpx` instrumenting (set environment variable `SKIP_INSTRUMENT_HTTPX="true"`) prior `elasticapm.instrument()` is called.

**To Reproduce**
```python3
import elasticapm
import httpx


def main():
    elasticapm.instrument()

    client = httpx.Client()
    elastic_apm_client = elasticapm.Client()

    elastic_apm_client.begin_transaction("httpx-context-manager-client-streaming")
    try:
        with client.stream("GET", url="https://example.com") as response:
            assert response
    finally:
        client.close()
        elastic_apm_client.end_transaction("httpx-context-manager-client-streaming")


if __name__ == "__main__":
    main()
```

**Expected result**
No exception is raised.

**Actual result**
```python3
Traceback (most recent call last):
  File "<...>/test.py", line 21, in <module>
    main()
  File "<...>/test.py", line 13, in main
    with client.stream("GET", url="https://example.com") as response:
  File "<...>/venv/lib/python3.8/site-packages/httpx/_client.py", line 1799, in __enter__
    self.response = self.client.send(
  File "<...>/venv/lib/python3.8/site-packages/elasticapm/instrumentation/packages/base.py", line 210, in call_if_sampling
    return self.call(module, method, wrapped, instance, args, kwargs)
  File "<...>/venv/lib/python3.8/site-packages/elasticapm/instrumentation/packages/httpx.py", line 42, in call
    request = kwargs.get("request", args[0])
IndexError: tuple index out of range
```

<br/>
<details>
<summary><b>See similar results for <code>httpx.AsyncClient.stream()</code></b></summary>

**To Reproduce**
```python3
import asyncio

import elasticapm
import httpx


async def main():
    elasticapm.instrument()

    client = httpx.AsyncClient()
    elastic_apm_client = elasticapm.Client()

    elastic_apm_client.begin_transaction("httpx-async-context-manager-client-streaming")
    try:
        async with client.stream("GET", url="https://example.com") as response:
            assert response
    finally:
        await client.aclose()
        elastic_apm_client.end_transaction(
            "httpx-async-context-manager-client-streaming",
        )


if __name__ == "__main__":
    asyncio.run(main())
```

**Actual result**
```python3
Traceback (most recent call last):
  File "<...>/test.py", line 23, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "<...>/test.py", line 15, in main
    async with client.stream("GET", url="https://example.com") as response:
  File "<...>/venv/lib/python3.8/site-packages/httpx/_client.py", line 1821, in __aenter__
    self.response = await self.client.send(
  File "<...>/venv/lib/python3.8/site-packages/elasticapm/instrumentation/packages/asyncio/httpx.py", line 42, in call
    request = kwargs.get("request", args[0])
IndexError: tuple index out of range
```
</details>
<br/>

**Environment**
- OS: Ubuntu 18.04.5 LTS
- Python version: 3.8.9
- Framework and version: `httpx==0.17.1` (also reproducible with current latest `httpx==0.19.0`)
- APM Server version: --
- Agent version: `elasticapm==6.4.0`

**Comment by beniwohli** [comment]
Hey @Tayum! Great find, thanks for the detailed bug report! I opened #1337 with a fix.
