### ISSUE TITLE
capture_exception raise TransportException and abort transaction

### ISSUE THREAD

**Issue by luipir** [elastic/apm-agent-python#1440]
**Describe the bug**: ...

During an exception handling capture_exeption fail to send data and as result transaction is aborted.
Seems the problem is decoding the data payload (memoryview type) to urllib3

This is the snippet:

    client.begin_transaction(transaction_type="script")
    try:
        with elasticapm.capture_span(name="a_name, labels={}):
                do_something_that _generate_exception()
       result = ''success'
    except Exception:
        message = traceback.format_exc()
        client.capture_exception()
        result = 'failed'
    finally:
        client.end_transaction(name="transaction_name", result=result)

result in the following trace:

`2021-12-22 12:22:56,737 [urllib3.connectionpool] [DEBUG] https://<hide>:443 "POST /intake/v2/events HTTP/1.1" 400 None
2021-12-22 12:22:56,828 [elasticapm.transport] [ERROR] Failed to submit message: 'HTTP 400: {"accepted":24,"errors":[{"message":"decode error: data read error: v2.errorRoot.Error: v2.errorEvent.Exception: v2.errorException.Stacktrace: []v2.stacktraceFrame: v2.stacktraceFrame.Vars: Read: unexpected value type: 0, error found in #10 byte of ...|l_value\\": NaN}, \\"pre|..., bigger context ...|,\\\\n      dtype=object)\\", \\"op\\": \\"x\\", \\"null_value\\": NaN}, \\"pre_context\\": [\\"    # type: (str, np.array[|...","document":"{\\"error\\": {\\"context\\": {\\"custom\\": {}}, \\"id\\": \\".....\\", \\"exception\\": {\\"message\\": \\"IndexError: list index out of range\\", \\"type\\": \\"IndexError\\", \\"module\\": \\"builtins\\", \\"stacktrace\\": [{\\"abs_path\\": \\"./stripe_delivery_pipeline.py\\", \\"filename\\": \\"stripe_delivery_pipeline.py\\", \\"module\\": \\"__main__\\", \\"function\\": \\"main\\", \\"lineno\\": 1970, \\"library_frame\\": false, \\"vars\\": {\\"elasticapm_span_labels\\": null, \\"elasticapm_span_name\\": \\"delivery-pipeline-main\\", \\"location\\": \\"undefined\\", \\"country\\": \\"undefined\\", \\"message\\": \\"Traceback (most recent call last):\\\\n  File \\\\\\"./stripe_delivery_pipeline.py\\\\\\", line 1970, in main\\\\n    status, message, country, location = real_main_multi_AOI(scene_set_id, scene_id_tag)\\\\n  File \\\\\\"./stri...\\", \\"status\\": \\"Failed\\", \\"result\\": null, \\"labels\\": {\\"pod_name\\": null, \\"job_id\\": null, \\"sceneset_id\\": \\".........\\", \\"scene_id_tag\\": null}, \\"     ...[cut]`

and

`Traceback (most recent call last):
  File "/home/lpirelli/miniconda/envs/py36/lib/python3.6/site-packages/elasticapm/transport/base.py", line 239, in _flush
    self.send(data)
  File "/home/lpirelli/miniconda/envs/py36/lib/python3.6/site-packages/elasticapm/transport/http.py", line 113, in send
    raise TransportException(message, data, print_trace=print_trace)
elasticapm.transport.exceptions.TransportException: HTTP 400: {"accepted":24,"errors":[{"message":"decode error: data read error: v2.errorRoot.Error: v2.errorEvent.Exception: v2.errorException.Stacktrace: []v2.stacktraceFrame: v2.stacktraceFrame.Vars: Read: unexpected value type: 0, error found in #10 byte of ...|l_value\": NaN}, \"pre|..., bigger context ...|,\\n      dtype=object)\", \"op\": \"x\", \"null_value\": NaN}, \"pre_context\": [\"    # type: (str, np.array[|...","document":"{\"error\": {\"context\": {\"custom\": {}}, \"id\": \"....\", \"exception\": {\"message\": \"IndexError: list index out of range\", \"type\": \"IndexError\", \"module\": \"builtins\", \"stacktra    ....[cut]` 

data payload in memory view is:

a= b'\x1f\x8b\x08\x00a\x11\xc3a\x02\xff\xed}{w#\xb7\xb1\xe7\xff\xfb)xx\xb3\xeb\xf1\x1e\x91\xc2\xb3\x1f:q\xb2\xb2F\xb6\x95;\x0fE\x92\x938\xe39}\xd0\xddh\xa93$\x9b\xe9&53\xf1z?\xfbV\x01\xfd\xe4C\xa44\x92F\xf6pr\xaf%u\x03\xe8z\xa1\xf0.... [cut]'

str(a, 'utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Environment (please complete the following information)**
- OS: Linux
- Python version:Python 3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 23:13:11)  [GCC 7.3.0] on linux
- APM Server version: elasticsearch==7.10.1, elastic-apm==6.4.0

**Comment by luipir** [comment]
this is my pip freeze:
`affine==2.3.0
appdirs==1.4.4
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1605217006479/work
astroid @ file:///tmp/build/80754af9/astroid_1592495913683/work
async-generator==1.10
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
autopep8 @ file:///tmp/build/80754af9/autopep8_1596578164842/work
backcall==0.2.0
beautifulsoup4==4.10.0
black==20.8b1
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1600454382015/work
boto3==1.16.28
botocore==1.19.28
cached-property==1.5.2
cachetools==4.1.1
certifi==2020.12.5
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1606236118475/work
chardet==3.0.4
click==7.1.2
click-plugins==1.1.1
cligj==0.7.1
confluent-kafka==1.7.0
coreapi==2.3.4+v20180822
coreschema==0.0.4
cycler==0.10.0
dataclasses==0.8
decorator==4.4.2
defusedxml==0.6.0
descartes==1.1.0
df2gspread==1.0.4
dicttoxml==1.7.4
elastic-apm==6.4.0
elasticsearch==7.10.1
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1605121927639/work/dist/entrypoints-0.3-py2.py3-none-any.whl
Fiona==1.8.13.post1
freezegun @ file:///home/conda/feedstock_root/build_artifacts/freezegun_1599336396063/work
furl==2.1.0
GDAL==3.0.2
geographiclib==1.50
geojson==2.5.0
geopandas @ file:///home/conda/feedstock_root/build_artifacts/geopandas_1594925563431/work
geopy==2.1.0
gitdb==4.0.9
GitPython==3.1.18
google==3.0.0
google-api-python-client==1.6.7
google-auth==1.23.0
google-auth-oauthlib==0.4.2
gspread==3.6.0
h5py==3.1.0
html5lib==1.1
httplib2==0.18.1
idna==2.10
imageio==2.9.0
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1607975943230/work
iniconfig @ file:///tmp/build/80754af9/iniconfig_1602780191262/work
ipdb==0.13.9
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1620912934572/work/dist/ipykernel-5.5.5-py3-none-any.whl
ipython @ file:///tmp/build/80754af9/ipython_1593447367857/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
isort @ file:///home/conda/feedstock_root/build_artifacts/isort_1602591728846/work
itypes==1.2.0
jedi @ file:///tmp/build/80754af9/jedi_1606932572482/work
Jinja2==2.11.2
jmespath==0.10.0
joblib==1.1.0
json2xml==3.6.0
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1602551949684/work
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1598486169312/work
jupyter-core @ file:///tmp/build/80754af9/jupyter_core_1606148976284/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
kiwisolver @ file:///tmp/build/80754af9/kiwisolver_1604014557000/work
lazy-object-proxy==1.4.3
lxml==4.6.3
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1602267314491/work
matplotlib @ file:///tmp/build/80754af9/matplotlib-base_1603373816490/work
mccabe==0.6.1
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1605115652956/work
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
more-itertools @ file:///tmp/build/80754af9/more-itertools_1605111547926/work
munch==2.5.0
mypy-extensions==0.4.3
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1602859080374/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert_1605401832871/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1602732862338/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1605195931949/work
networkx==2.5.1
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1605103640761/work
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1603487797006/work
oauth2client==4.1.3
oauthlib==3.1.0
olefile==0.46
opencv-python==4.4.0.46
opencv-python-headless==4.5.4.58
orderedmultidict==1.0.1
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1607785313469/work
pandas @ file:///tmp/build/80754af9/pandas_1602088135163/work
pandocfilters==1.4.2
parso==0.7.0
pathspec==0.8.1
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow @ file:///tmp/build/80754af9/pillow_1603822238230/work
pluggy==0.13.1
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1605543085815/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1602524994744/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1605560620615/work/dist/ptyprocess-0.6.0-py2.py3-none-any.whl
py @ file:///tmp/build/80754af9/py_1607971587848/work
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
Pygments @ file:///tmp/build/80754af9/pygments_1604103097372/work
pylint @ file:///tmp/build/80754af9/pylint_1598624022510/work
pyparsing==2.4.7
pyproj==2.6.1.post1
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1605115583744/work
pytest==6.2.4
pytest-mock==3.5.0
python-dateutil==2.8.1
python-dotenv==0.15.0
pytz @ file:///tmp/build/80754af9/pytz_1606604771399/work
PyWavelets==1.1.1
pyzmq==20.0.0
rasterio==1.1.0
rasterstats==0.15.0
regex @ file:///tmp/build/80754af9/regex_1606772707535/work
requests==2.25.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
retry==0.9.2
rsa==4.6
Rtree==0.9.4
s3transfer==0.3.3
scikit-image==0.17.2
scikit-learn==0.24.2
scipy==1.5.4
seaborn==0.11.2
Send2Trash==1.5.0
Shapely @ file:///tmp/build/80754af9/shapely_1599817091771/work
simplejson==3.17.3
six @ file:///tmp/build/80754af9/six_1605205335545/work
slacker==0.14.0
smmap==5.0.0
snuggs==1.4.7
soupsieve==2.2.1
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1605116895878/work
testpath==0.4.4
threadpoolctl==3.0.0
tifffile==2020.9.3
toml==0.10.2
torch==1.7.1
tornado @ file:///tmp/build/80754af9/tornado_1606942266872/work
tqdm==4.54.0
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1602702424206/work
uritemplate==3.0.1
urllib3==1.26.2
utm==0.7.0
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
wrapt==1.11.2
xmltodict==0.11.0
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1603668650351/work
`

**Comment by basepi** [comment]
I haven't had a chance to test this yet, but can you define what you mean by "and as result transaction is aborted."? If urllib3 is indeed throwing an error because of a payload it can't decode correctly, that's one thing. But when the transport raises an error, it should be logged but I think the transaction should still be reported.

**Comment by luipir** [comment]
Hi @basepi sorry for my delay... just come back to work. Need some time to come back on this issue. I've give you a feedback as soon as possible

**Comment by basepi** [comment]
@luipir Any luck finding some time here?

**Comment by luipir** [comment]
not yet sorry :/

**Comment by rwikdutta** [comment]
Hi,
Any update on this? This is affecting me as well

**Comment by basepi** [comment]
@rwikdutta Can you share any stacktraces and additional information? Want to make sure I have a clear idea of the behavior.
