### ISSUE TITLE
Failed monitoring sqs_queue.delete_message and sqs_queue.send_message

### ISSUE THREAD

**Issue by josef-cech-acc** [elastic/apm-agent-python#1480]
**Describe the bug**: 
During capture_metric we manually remove messages from SQS - we get errors about missing key MessageAttribues
There is no way how to put MessageAttributes  into delete_messages 
   - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Queue.delete_messages
   - https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_DeleteMessageBatchRequestEntry.html

The same bug appears using send_messages without MessageAttributes (it is only optional) 

throw an error : 
```
Ignored valueTraceback (most recent call last):   File "/var/task/accolade_tracing/tracing_lambda.py", line 173, 
in inner_wrapper     result = func(event, context)   File "/var/task/src/main.py", line 171,
 in email_channel_worker     return handler.handle(event=event, context=context)   File "/var/task/src/handlers/email_sender/email_sender_handler.py", line 29,
 in handle     if self._process_from_subscriber(subscriber):   File "/var/task/src/handlers/email_sender/email_sender_handler.py", line 51,
 in _process_from_subscriber     subscriber.process(_deliver_email, max_count=1)   File "/var/task/accolade_eventbus/subscriber.py", line 83, 
in process     self._channel_receiver.delete(acp_event)   File "/var/task/accolade_eventbus/subscriber.py", line 62,
 in delete     Entries=[{'Id': message_id, 'ReceiptHandle': sqs_receipt_handle}])   File "/var/task/boto3/resources/factory.py", line 580, in do_action     response = action(self, *args, **kwargs)   File "/var/task/boto3/resources/action.py", line 88, 
in __call__     response = getattr(parent.meta.client, operation_name)(*args, **params)   File "/var/task/botocore/client.py", line 395, 
in _api_call     return self._make_api_call(operation_name, kwargs)   File "/var/task/elasticapm/instrumentation/packages/base.py", line 210, 
in call_if_sampling     return self.call(module, method, wrapped, instance, args, kwargs)   File "/var/task/elasticapm/instrumentation/packages/botocore.py", line 93,
 in call     span_modifiers[service](span, args, kwargs)   File "/var/task/elasticapm/instrumentation/packages/botocore.py", line 194,
 in modify_span_sqs     if len(message["MessageAttributes"]) + attributes_count <= SQS_MAX_ATTRIBUTES: 
KeyError: 'MessageAttributes'
```

https://github.com/elastic/apm-agent-python/blob/main/elasticapm/instrumentation/packages/botocore.py#L194

`

**To Reproduce**

```
sqs_queue = sqs.Queue(queue_url)
sqs_queue.delete_messages(Entries=[{'Id': message_id, 'ReceiptHandle': sqs_receipt_handle }])

```

**Environment (please complete the following information)**
- Python version: 3.8
- Framework and version [e.g. Django 2.1]: boto3
- Lambda layer : arn:aws:lambda:us-east-1:267093732750:layer:elastic-apm-extension-ver0-0-3-x86_64:3

**Comment by basepi** [comment]
I think this is related to our mishandling of MessageAttributes as pointed out here: https://github.com/elastic/apm/pull/614

This is on my list for the set of lambda improvements I'm working on now.
