### ISSUE TITLE
Error in instrumentation on boto3 sqs client function send_message_batch

### ISSUE THREAD

**Issue by hccruz-topaz** [elastic/apm-agent-python#1572]
**Bug**
Error in instrumentation on boto3 sqs client function send_message_batch when do not define non required parameter MessageAttributes in entries.

[SQS.Client.send_message_batch](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Client.send_message_batch)

**To Reproduce**
instrumet code
start a transaction (without a started transaction code works fine)
send_bactch_message without Entries.MessageAttributes parameter

```
import uuid
import boto3
import elasticapm
from elasticapm import Client


if __name__ == '__main__':
    elasticapm.instrument()
    apm_client = Client(service_name=apm_info['SERVICE_NAME'],
                        server_url=apm_info['SERVER_URL'],
                        secret_token=apm_info['SECRET_TOKEN'],
                        environment=apm_info['Environment_name'])

    elasticapm.instrument()
    apm_client.begin_transaction(transaction_type="script")
    try:
        sqs_client = boto3.client('sqs')
        sqs_url = MY_SQS_URL
        entries = [dict(Id=uuid.uuid4().hex, MessageBody=str(i)) for i in range(10)]
        sqs_client.send_message_batch(QueueUrl=sqs_url, Entries=entries)
    except:
        apm_client.apm_client.capture_exception()
    apm_client.end_transaction(name="producer", result='success')
```
**workaround**
Definining Parameter Entries.MessageAttributes={} instrumentation works fine.

```
import uuid
import boto3
import elasticapm
from elasticapm import Client


if __name__ == '__main__':
    elasticapm.instrument()
    apm_client = Client(service_name=apm_info['SERVICE_NAME'],
                        server_url=apm_info['SERVER_URL'],
                        secret_token=apm_info['SECRET_TOKEN'],
                        environment=apm_info['Environment_name'])

    elasticapm.instrument()
    apm_client.begin_transaction(transaction_type="script")
    try:
        sqs_client = boto3.client('sqs')
        sqs_url = MY_SQS_URL
        entries = [dict(Id=uuid.uuid4().hex, MessageBody=str(i), MessageAttributes={}) for i in range(10)]
        sqs_client.send_message_batch(QueueUrl=sqs_url, Entries=entries)
    except:
        apm_client.apm_client.capture_exception()
    apm_client.end_transaction(name="producer", result='success')
```

`
**Environment (please complete the following information)**
- OS: Release Linux Mint 20.3 Una 64-bit, Kernel Linux 5.13.0-41-generic x86_64, MATE 1.26.0
- Python version: 3.8.10 
- APM Server version: 8.1.2
- Agent version: elastic-apm==6.9.1

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

```
Traceback (most recent call last):
  File "/home/user/test/python/eapm_bug//tests/apm_bug.py", line 25, in <module>
    sqs_client.send_message_batch(QueueUrl=sqs_url, Entries=entries)
  File "/home/user/test/python/eapm_bug//venv/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/user/test/python/eapm_bug//venv/lib/python3.8/site-packages/elasticapm/instrumentation/packages/base.py", line 210, in call_if_sampling
    return self.call(module, method, wrapped, instance, args, kwargs)
  File "/home/user/test/python/eapm_bug//venv/lib/python3.8/site-packages/elasticapm/instrumentation/packages/botocore.py", line 93, in call
    span_modifiers[service](span, args, kwargs)
  File "/home/user/test/python/eapm_bug//venv/lib/python3.8/site-packages/elasticapm/instrumentation/packages/botocore.py", line 194, in modify_span_sqs
    if len(message["MessageAttributes"]) + attributes_count <= SQS_MAX_ATTRIBUTES:
KeyError: 'MessageAttributes'

Process finished with exit code 1

```
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    elastic-apm[flask]>=6.8.1,<7
    ```
  </details>

**Comment by beniwohli** [comment]
@hccruz-topaz thanks for opening the issue and the detailed report! I opened a PR with a fix here: #1573.
