### ISSUE TITLE
enabling sniff_on_start in elasticsearch() breaks elasticserach instrumentation

### ISSUE THREAD

**Issue by soudhaf** [elastic/apm-agent-python#1615]
**Describe the bug**:
sniff_on_start in elasticsearch with apm enabled fails the request due to a null span object
```python
ERROR File /opt/venv/lib/python3.9/site-packages/django/utils/log.py, line 224, Internal Server Error: /api/test_view
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/api/views.py", line 592, in get
    es = Elasticsearch(hosts=["elasticsearch"],sniff_on_start=True)
  File "/opt/venv/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 205, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/elasticsearch/transport.py", line 200, in __init__
    self.sniff_hosts(True)
  File "/opt/venv/lib/python3.9/site-packages/elasticsearch/transport.py", line 365, in sniff_hosts
    node_info = self._get_sniff_data(initial)
  File "/opt/venv/lib/python3.9/site-packages/elasticsearch/transport.py", line 308, in _get_sniff_data
    _, headers, node_info = c.perform_request(
  File "/opt/venv/lib/python3.9/site-packages/elasticapm/instrumentation/packages/base.py", line 210, in call_if_sampling
    return self.call(module, method, wrapped, instance, args, kwargs)
  File "/opt/venv/lib/python3.9/site-packages/elasticapm/instrumentation/packages/elasticsearch.py", line 58, in call
    self._update_context_by_request_data(span.context, instance, args, kwargs)
AttributeError: 'NoneType' object has no attribute 'context'

```

**To Reproduce**

1. setup an elasticsearch instance or a cluser and a django app
2. create test view to create elasticsearch connection instance
 ```python
from elasticsearch import Elasticsearch
from django.http import HttpResponse
from django.views import View

class TestView(View):
    def get(self, request, *args, **kwargs):
        es = Elasticsearch(hosts=["elasticsearch"],sniff_on_start=True)
        return HttpResponse("Success !")
```
4. curl that view 

**Environment**
- OS:  debian buster docker
- Python version: 3.9
- Framework and version : django 3.2.15
- elasticserach-py: 7.17.14
- elasticsearch: 7.15.3
- APM Server version: 7.10.2
- Agent version: 6.10.1

**Comment by basepi** [comment]
Thanks for the report. Should be easy to check if the span is `None` to prevent this error.
