### ISSUE TITLE
Not getting any events on the apm server

### ISSUE THREAD

**Issue by debugger22** [elastic/apm-agent-python#188]
The `elasticapm check` command fails with following error.
```
$ python manage.py elasticapm check
Service name and secret token are set, good job!

DEBUG mode is disabled! Looking good!

Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.virtualenvs/backend/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.virtualenvs/backend/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/.virtualenvs/backend/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/.virtualenvs/backend/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/.virtualenvs/backend/lib/python3.5/site-packages/elasticapm/contrib/django/management/commands/elasticapm.py", line 104, in handle
    )(self, subcommand, **options)
  File "/home/ubuntu/.virtualenvs/backend/lib/python3.5/site-packages/elasticapm/contrib/django/management/commands/elasticapm.py", line 207, in handle_check
    middleware = list(getattr(settings, 'MIDDLEWARE', getattr(settings, 'MIDDLEWARE_CLASSES', [])))
TypeError: 'NoneType' object is not iterable
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

**Comment by beniwohli** [comment]
Hi @debugger22, thanks for the report! As far as I can tell, the error indicates that you have neither a [`MIDDLEWARE`](https://docs.djangoproject.com/en/2.0/ref/settings/#middleware) (Django 1.10+) nor a [`MIDDLEWARE_CLASSES`](https://docs.djangoproject.com/en/1.11/ref/settings/#middleware-classes) (up to Django 1.11) setting in your `settings.py`. Can you check if either of those exists and isn't set to `None`?

**Comment by debugger22** [comment]
Yes, my settings.py has `MIDDLEWARE_CLASSES`.

**Comment by beniwohli** [comment]
Ah, I think I know what's going on. `django.conf.MIDDLEWARE` is already there in 1.11, but due to the fact that you use `MIDDLEWARE_CLASSES`, it is set to `None`. I'll open a PR to fix it ASAP :)
