### ISSUE TITLE
Starlette/FastAPI/Uvicorn capture_body causes requests to fail

### ISSUE THREAD

**Issue by karski** [elastic/apm-agent-python#1965]
**Describe the bug**: When apm client `CAPTURE_BODY` is ***NOT*** set to `"off"`, requests where the body is captured fail with the error:
`Exception in ASGI application`
`Unexpected message received: http.request`

**To Reproduce**

1. Update to Starlette 0.36.2 or FastAPI 0.109.1 
2. Configure the apm client with `make_apm_client({'CAPTURE_BODY': 'all'`}`
3. Make any HTTP request to the server
4. HTTP response is broken (empty body, possibly 502 error depending on proxy setups)
5. Observe error messages in server logs
6. Configure the apm client with `make_apm_client({'CAPTURE_BODY': 'off'`}`
7. HTTP requests succeed

**Environment (please complete the following information)**
- OS: Linux
- Python version: 3.10.12
- Framework and version [e.g. Django 2.1]: FastAPI 0.109.1
- APM Server version: (actually fails before reaching server, so server is irrelevant)
- Agent version: elastic-apm 6.20.0

**Additional context**

I'm guessing this has to do with changes introduced to address a DOS vulnerability?
https://github.com/advisories/GHSA-93gm-qmq6-w238

Full error message:
```
[ uvicorn.error  ] ERROR    - Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 192, in __call__
  |     await response(scope, wrapped_receive, send)
  |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 257, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/usr/local/lib/python3.10/site-packages/elasticapm/contrib/starlette/__init__.py", line 193, in __call__
    |     await self.app(scope, _request_receive or receive, wrapped_send)
    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/usr/local/lib/python3.10/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 264, in __call__
    |     await wrap(partial(self.listen_for_disconnect, receive))
    |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 260, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 237, in listen_for_disconnect
    |     message = await receive()
    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 56, in wrapped_receive
    |     raise RuntimeError(f"Unexpected message received: {msg['type']}")
    | RuntimeError: Unexpected message received: http.request
    +------------------------------------
```

**Comment by basepi** [comment]
Thanks for the report! I'm a little bit surprised the nightly tests didn't catch this -- we'll have to look into this, because we definitely test capture_body in the tests: https://github.com/elastic/apm-agent-python/blob/c7bde0ae2cb509f84d4605400917229828b2dc2e/tests/contrib/asyncio/starlette_tests.py#L170-L202

Perhaps the body is empty there and that's all we need to do to spruce up that test. In any case, we'll get this fixed.

**Comment by xrmx** [comment]
Tried to extend tests a bit but can't reproduce the issue:

```
diff --git a/tests/contrib/asyncio/starlette_tests.py b/tests/contrib/asyncio/starlette_tests.py
index fcd7d0de..5bb0b4a0 100644
--- a/tests/contrib/asyncio/starlette_tests.py
+++ b/tests/contrib/asyncio/starlette_tests.py
@@ -167,8 +167,9 @@ def test_get(app, elasticapm_client):
     assert span["name"] == "test"
 
 
-@pytest.mark.parametrize("elasticapm_client", [{"capture_body": "all"}], indirect=True)
-def test_post(app, elasticapm_client):
+@pytest.mark.parametrize("elasticapm_client", [{"capture_body": "all"},], indirect=True)
+@pytest.mark.parametrize(["payload", "body"], [({"foo": "bar"}, "foo=bar"), ({}, "")])
+def test_post(app, elasticapm_client, payload, body):
     client = TestClient(app)
 
     response = client.post(
@@ -178,10 +179,11 @@ def test_post(app, elasticapm_client):
             constants.TRACESTATE_HEADER_NAME: "foo=bar,bar=baz",
             "REMOTE_ADDR": "127.0.0.1",
         },
-        data={"foo": "bar"},
+        data=payload,
     )
 
     assert response.status_code == 200
+    assert response.content == str(len(body)).encode()
 
     assert len(elasticapm_client.events[constants.TRANSACTION]) == 1
     transaction = elasticapm_client.events[constants.TRANSACTION][0]
@@ -197,7 +199,7 @@ def test_post(app, elasticapm_client):
     request = transaction["context"]["request"]
     assert request["method"] == "POST"
     assert request["socket"] == {"remote_address": "127.0.0.1"}
-    assert request["body"] == "foo=bar"
+    assert request["body"] == body
 
     assert span["name"] == "test"
 
```

**Comment by xrmx** [comment]
I cannot replicate the issue with the following code running under uvicorn:

```
from fastapi import FastAPI, Request
from elasticapm.contrib.starlette import ElasticAPM, make_apm_client
from pydantic import BaseModel

apm = make_apm_client({"SERVICE_NAME": "service", "API_KEY": "", "SERVER_URL": """, "CAPTURE_BODY": "all"})

app = FastAPI()
app.add_middleware(ElasticAPM, client=apm)

class Foo(BaseModel):
    name: str

@app.post("/foo/")
async def fooroute(foo: Foo):
    return foo


@app.post("/")
async def root(request: Request):
    return {"hello": "there"}
```

With the following invocations:

```
curl -d '{}' -H "Content-Type: application/json" -X POST http://localhost:8000/
{"hello":"there"}
curl -d '{}' -H "Content-Type: application/json" -X POST http://localhost:8000/foo/
{"detail":[{"type":"missing","loc":["body","name"],"msg":"Field required","input":{},"url":"https://errors.pydantic.dev/2.6/v/missing"}]}
curl -d '{"name": "my name"}' -H "Content-Type: application/json" -X POST http://localhost:8000/foo/
{"name":"my name"}
```

@karski any hint on what you may be doing differently?

**Comment by karski** [comment]
I saw the same behavior last week on my system. I will try to make a
cleaner environment to figure out the root issue.

**Comment by Elfpkck** [comment]
@karski Could you specify that another middleware? Because I still have the error.

**Comment by karski** [comment]
After experimenting, it seems like any time you apply more than
one BaseHTTPMiddleware, the behavior pops up. One (or none) instances of
BaseHTTPMiddleware in the chain behaves as expected with APM body logging
on, but two or more break. I'm guessing it has something to do with the way
the APM mocks the body interacting with the way BaseHTTPMiddleware wraps
the body, but I was unable to figure it out.
