### ISSUE TITLE
threading exception under flask

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-agent-python#222]
Per elastic/apm-integration-testing/#73, the agent is apparently trying to join a thread that it shouldn't under flask.

env:
```
# pip freeze
blinker==1.4
certifi==2018.4.16
click==6.7
elastic-apm==2.1.1
Flask==1.0.2
gunicorn==19.8.1
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
urllib3==1.23
Werkzeug==0.14.1
```

flask says:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1834, in finalize_request
    request_finished.send(self, response=response)
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/elasticapm/contrib/flask/__init__.py", line 151, in request_finished
    self.client.end_transaction(rule, result)
  File "/usr/local/lib/python3.6/site-packages/elasticapm/base.py", line 257, in end_transaction
    self._collect_transactions()
  File "/usr/local/lib/python3.6/site-packages/elasticapm/base.py", line 297, in _collect_transactions
    self._stop_send_timer()
  File "/usr/local/lib/python3.6/site-packages/elasticapm/base.py", line 324, in _stop_send_timer
    self._send_timer.join()
  File "/usr/local/lib/python3.6/threading.py", line 1051, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
```

Reproduceable using https://github.com/elastic/apm-integration-testing/issues/73#issuecomment-394832586

**Comment by beniwohli** [comment]
I wasn't able to reproduce this. Closing.
