### ISSUE TITLE
Problem validating JSON document against schema: I[#] S[#] doesn't validate with "transaction#"   I[#/service/name] S[#/properties/service/properties/name/type] expected string, but got null

### ISSUE THREAD

**Issue by ksmets** [elastic/apm-agent-python#224]
I'm trying to get started with elastic-apm[flask] (version 2.1.1, on Python 3.6.5) and apm-server (6.2.4) running in docker.

My virtualenv after running, `pip install Flask elastic-apm[flask]` looks like:
```
blinker==1.4
certifi==2018.4.16
click==6.7
elastic-apm==2.1.1
Flask==1.0.2
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
pyspark==2.2.1
urllib3==1.23
Werkzeug==0.14.1
```

My docker-compose.yml:

```
version: '3.6'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    depends_on:
    - elasticsearch
    ports:
    - '5601:5601'

  apm-server:
    image: docker.elastic.co/apm/apm-server:6.2.4
    depends_on:
    - elasticsearch
    ports:
    - '8200:8200'
```

Kibana apm dashboard shows status of apm-server is green.

```
from elasticapm.contrib.flask import ElasticAPM
from flask import Flask

app = Flask(__name__)
apm = ElasticAPM(app)

@app.route("/")
def hello():
    return "Hello World!
```

I use the following command to start `hello.py`
```
env FLASK_APP=hello.py flask run
```

When accessing doing `curl localhost:5000`, I see "Hello, world!" printed, but the following error occurs:

```
127.0.0.1 - - [08/Jun/2018 16:27:46] "GET / HTTP/1.1" 200 -
HTTP 400: Problem validating JSON document against schema: I[#] S[#] doesn't validate with "transaction#"
  I[#/service/name] S[#/properties/service/properties/name/type] expected string, but got null
Failed to submit message: '<no message value>'
Traceback (most recent call last):
  File "/Users/ksmets/.virtualenvs/elastic-apm-flask/lib/python3.6/site-packages/elasticapm/transport/http_base.py", line 45, in send_sync
    url = self.sync_transport.send(self, data, headers)
  File "/Users/ksmets/.virtualenvs/elastic-apm-flask/lib/python3.6/site-packages/elasticapm/transport/http.py", line 77, in send
    raise TransportException(message, data, print_trace=print_trace)
elasticapm.transport.base.TransportException: HTTP 400: Problem validating JSON document against schema: I[#] S[#] doesn't validate with "transaction#"
  I[#/service/name] S[#/properties/service/properties/name/type] expected string, but got null
```

```
apm-server_1     | 2018-06-08T14:43:46.346Z	ERROR	[request]	beater/handlers.go:384	error handling request	{"request_id": "b448367c-c79b-46cf-8e16-9a9fb08726c1", "error": "Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#/service/name] S[#/properties/service/properties/name/type] expected string, but got null"}
apm-server_1     | 2018-06-08T14:43:46.346Z	INFO	[request]	beater/handlers.go:150	handled request	{"request_id": "b448367c-c79b-46cf-8e16-9a9fb08726c1", "response_code": 400, "method": "POST", "URL": "/v1/transactions", "content_length": 676, "remote_address": "172.20.0.1", "user_agent": "elasticapm-python/2.1.1"
```

Kibana apm dashboard shows no apm data is flowing in.

Any ideas?

**Comment by graphaelli** [comment]
@ksmets Thanks for getting in touch.  This error indicates that the service name is not set.

One way to do that with your code:
```
app = Flask(__name__)
app.config['ELASTIC_APM'] = {
    'SERVICE_NAME': 'my-app',
}
apm = ElasticAPM(app)
```

Check out our [flask configuration docs](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#flask-configuration) 
for more options.

**Comment by ksmets** [comment]
Thx, that indeed was the missing piece of the puzzle: `env FLASK_APP=hello.py ELASTIC_APM_SERVICE_NAME=hello flask run`

**Comment by sebd44** [comment]
hi all i have the same problem, but when i start the app it runs it in the loopback 

env FLASK_APP=hello.py ELASTIC_APM_SERVICE_NAME=hello flask run

http://127.0.0.1:5000/ 

but i want to run it like this 0.0.0.0

if __name__ == "__main__":
    app.run(host='0.0.0.0', port= 5000)



that is how i got in the hello,py file that i have
how can i run this command with the 0.0.0.0 instead of the 127.0.0.1??

env FLASK_APP=hello.py ELASTIC_APM_SERVICE_NAME=hello flask run
