### ISSUE TITLE
Failed to submit message: 'HTTP 401: invalid token'

### ISSUE THREAD

**Issue by DwijadasDey** [elastic/apm-agent-python#339]
I have the following sample python flask apps that generates 'token error' although tokens are same in both the APM server and the apps.

```
app.py
-------
....
....
apm = ElasticAPM(app, SERVER_URL='http://DOMAIN:8200', SERVICE_NAME='portfolio', SECRET_TOKEN='*****QB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bp***', LOGGING=False)
....
....
```

APM server config:
--------------------
```
apm-server:
  host: 0.0.0.0:8200
  secret_token: '*****QB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg**'
....
....
```

The actual error message is:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/elasticapm/transport/base.py", line 192, in send_sync
    self.sync_transport.send(self, data)
  File "/usr/local/lib/python3.6/dist-packages/elasticapm/transport/http.py", line 63, in send
    raise TransportException(message, data, print_trace=print_trace)
elasticapm.transport.base.TransportException: HTTP 401: invalid token
```

Where could be the issue ?

**Comment by beniwohli** [comment]
Hey @DwijadasDey 

We never were able to reproduce this issue on our side. I'll close this for now. Feel free to re-open if you still encounter this issue and/or have more information
