### ISSUE TITLE
Configuring restricted APP_NAME pattern leads to 500 during runtime. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-agent-python#48]
I configured a restricted pattern for the `APP_NAME` containing an `*` leading to a Server Error with following exception. This prevents a Django app from working properly when the `APP_NAME` is misconfigured. 

```
Unable to process log entry: 'DjangoClient' object has no attribute 'filter_exception_types_dict'
Traceback (most recent call last):
  File "/Users/simitt/.pyenv/versions/django-test-3.6.2/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/simitt/.pyenv/versions/django-test-3.6.2/lib/python3.6/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/Users/simitt/.pyenv/versions/django-test-3.6.2/lib/python3.6/site-packages/elasticapm/contrib/django/middleware/__init__.py", line 157, in process_request
    self.client.begin_transaction("request")
  File "/Users/simitt/.pyenv/versions/django-test-3.6.2/lib/python3.6/site-packages/elasticapm/base.py", line 442, in begin_transaction
    self.instrumentation_store.begin_transaction(transaction_type)
AttributeError: 'DjangoClient' object has no attribute 'instrumentation_store'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/simitt/.pyenv/versions/django-test-3.6.2/lib/python3.6/site-packages/elasticapm/contrib/django/handlers.py", line 59, in actually_do_stuff
    client.capture('Exception', exc_info=exc_info, request=request)
  File "/Users/simitt/.pyenv/versions/django-test-3.6.2/lib/python3.6/site-packages/elasticapm/contrib/django/client.py", line 200, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/Users/simitt/.pyenv/versions/django-test-3.6.2/lib/python3.6/site-packages/elasticapm/base.py", line 279, in capture
    data = self.build_msg_for_logging(event_type, data, date, extra, stack, **kwargs)
  File "/Users/simitt/.pyenv/versions/django-test-3.6.2/lib/python3.6/site-packages/elasticapm/base.py", line 178, in build_msg_for_logging
    if self._filter_exception_type(result):
  File "/Users/simitt/.pyenv/versions/django-test-3.6.2/lib/python3.6/site-packages/elasticapm/base.py", line 332, in _filter_exception_type
    if exc_type in self.filter_exception_types_dict:
AttributeError: 'DjangoClient' object has no attribute 'filter_exception_types_dict'
```

I am testing with Django-1.11.5 and python 3.6.2.

**Comment by beniwohli** [comment]
Good find (and sorry for the long response time). What I'm wondering is how we should handle this properly. I want to avoid to outright terminate the process if the config doesn't validate.

One option is to disable the automatic wiring up of the agent if the config isn't valid, that should avoid this code to be run

**Comment by ruflin** [comment]
I think if a config is wrong, the app should stop. This will make people to search for the problem and fix it. Otherwise they will run the app and only see the error much later.

**Comment by beniwohli** [comment]
The problem is, we're a library, not an app. I _really_ want to avoid taking down a user's website because they forgot to set the `ELASTIC_APM_APP_NAME` environment variable in production.

**Comment by ruflin** [comment]
I think there should be a difference between "not set" and "set it wrong". I agree that when it's not set we should log an error but not stop the app. But if it is set but "wrong" I would stop even in production.

**Comment by beniwohli** [comment]
@watson @roncohen what's your viewpoint on this? Should we fail loudly and make the app exit if the configuration is wrong?

**Comment by watson** [comment]
@beniwohli Good question. First off I think it depends on the stack. So I don't think we should make this a rule across the agents. In Node.js I've been going back and forth on this as well. Normally I would always throw if the arguments are wrong. But in this case I'm a bit on the fence

**Comment by simitt** [comment]
In my opinion we should avoid having a wrong configuration of a monitoring tool bringing down a whole system. 
I agree though that it might vary between stacks. In any app that might be shipped to some customer I'd say it is a no-go, since the whole software would be broken and could only be fixed with being shipped again.

**Comment by beniwohli** [comment]
Sorry for the long wait on this @simitt!
