### ISSUE TITLE
TypeError in elasticapm urllib

### ISSUE THREAD

**Issue by src-pwd** [elastic/apm-agent-python#555]
In Django app, when `elasticapm.contrib.django.middleware.TracingMiddleware` is enabled, HTTP requests fail with:
```
File ".env/lib/python3.6/site-packages/elasticapm/instrumentation/packages/urllib.py", line 51, in request_host
    port = int(port)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Full trace:
```
Traceback (most recent call last):
  File ".env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File ".env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File ".env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File ".env/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File ".env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File ".env/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "spa_api/endpoint.py", line 28, in dispatch
    response = super(APIEndpoint, self).dispatch(request, *args, **kwargs)
  File ".env/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "spa_api/endpoint.py", line 65, in authorized_function
    return original_function(*args, **kwargs)
  File "spa_api/endpoint.py", line 94, in resolve_shop_func
    return original_function(*args, **kwargs)
  File "spa_api/endpoints/shop_shopify_recurring_charge.py", line 34, in get
    real_charge = recurring_charge.sync()
  File "core/shopify/recurring_charge.py", line 77, in sync
    self._recurring_charge.shopify_id
  File "main/providers/utils/shopify/handle_common_errors.py", line 13, in new_function
    return fn(*args, **kwargs)
  File "main/providers/shopify/recurring_charge.py", line 35, in get_by_id
    return shopify.RecurringApplicationCharge.find(id_=charge_id)
  File ".env/lib/python3.6/site-packages/pyactiveresource/activeresource.py", line 383, in find
    return cls._find_single(id_, **kwargs)
  File ".env/lib/python3.6/site-packages/pyactiveresource/activeresource.py", line 486, in _find_single
    return cls._build_object(cls.connection.get(path, cls.headers),
  File ".env/lib/python3.6/site-packages/pyactiveresource/connection.py", line 329, in get
    return self.format.decode(self._open('GET', path, headers=headers).body)
  File ".env/lib/python3.6/site-packages/shopify/base.py", line 23, in _open
    self.response = super(ShopifyConnection, self)._open(*args, **kwargs)
  File ".env/lib/python3.6/site-packages/pyactiveresource/connection.py", line 286, in _open
    http_response = self._handle_error(self._urlopen(request))
  File ".env/lib/python3.6/site-packages/pyactiveresource/connection.py", line 316, in _urlopen
    return urllib.request.urlopen(request, timeout=self.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File ".env/lib/python3.6/site-packages/elasticapm/instrumentation/packages/base.py", line 141, in call_if_sampling
    return self.call(module, method, wrapped, instance, args, kwargs)
  File ".env/lib/python3.6/site-packages/elasticapm/instrumentation/packages/urllib.py", line 74, in call
    host = request_host(request_object)
  File ".env/lib/python3.6/site-packages/elasticapm/instrumentation/packages/urllib.py", line 51, in request_host
    port = int(port)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by beniwohli** [comment]
Hi @src-pwd. Thanks for opening the issue! It looks like this is a duplicate of #553. I'll close this in favor of the other ticket.
