### ISSUE TITLE
Exception json.decoder.JSONDecodeError with empty payload

### ISSUE THREAD

**Issue by trancee** [elastic/apm-agent-python#562]
**Describe the bug**:
It seems that ElasticAPM causes an exception if the payload in the body is empty:
```
Exception in thread eapm conf updater:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/hidio/git/api/env/lib/python3.7/site-packages/elasticapm/utils/threading.py", line 79, in run
    rval = self._function(*self._args, **self._kwargs)
  File "/home/hidio/git/api/env/lib/python3.7/site-packages/elasticapm/conf/__init__.py", line 402, in update_config
    new_version, new_config, next_run = transport.get_config(agent.config.config_version, keys)
  File "/home/hidio/git/api/env/lib/python3.7/site-packages/elasticapm/transport/http.py", line 135, in get_config
    return response.headers.get("Etag"), json_encoder.loads(body.decode("utf-8")), max_age
  File "/home/hidio/git/api/env/lib/python3.7/site-packages/elasticapm/utils/json_encoder.py", line 67, in loads
    return json.loads(value, object_hook=better_decoder)
  File "/usr/local/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**

1. Not sure where the payload actually comes from but if you make it empty (b'') this will cause the issue.

**Expected behavior**:
Do not run json_encoder.loads() on an empty body and continue successfully without raising an exception.

**Environment (please complete the following information)**
- OS: CentOS 7
- Python version: 3.7.4
- Framework and version: Flask
- APM Server version: 7.3.0
- Agent version: 5.1.0

**Additional context**
An easy fix would be to check if the body is empty and either skip it completely, or continue parsing a valid JSON string instead:
```
return response.headers.get("Etag"), json_encoder.loads(body.decode("utf-8") or "{}"), max_age
```

**Comment by beniwohli** [comment]
@trancee great catch, thanks for the detailed bug report! I'll get a fix out ASAP!

**Comment by beniwohli** [comment]
@trancee would it be possible to figure out what the response code from the APM Server was when this happened? Theoretically, the APM Server shouldn't return empty responses for anything other than `304` status codes, which we handle explicitly in the code.

I'll still add graceful handling for an empty response, but it might be that there's also a bug in APM Server in play here.

**Comment by trancee** [comment]
> @trancee would it be possible to figure out what the response code from the APM Server was when this happened? Theoretically, the APM Server shouldn't return empty responses for anything other than `304` status codes, which we handle explicitly in the code.

Sorry for the late response, but just for completeness I got the status code `202` in that case. Maybe it helps.

**Comment by beniwohli** [comment]
This is now released in v5.1.1

**Comment by JBauto** [comment]
I'm getting this issue with elastic-apm==5.10.0.

- OS: Fedora 32
- Python version: 3.8.6
- Framework and version: FastAPI==0.61.2 & Uvicorn==0.12.2
- APM Server version: 7.10
- Agent version: 5.10.0

The error is basically the same,

```
Exception in thread eapm conf updater:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib64/python3.8/site-packages/elasticapm/utils/threading.py", line 80, in run
    rval = self._function(*self._args, **self._kwargs)
  File "/usr/local/lib64/python3.8/site-packages/elasticapm/conf/__init__.py", line 684, in update_config
    new_version, new_config, next_run = self.transport.get_config(self.config_version, keys)
  File "/usr/local/lib64/python3.8/site-packages/elasticapm/transport/http.py", line 159, in get_config
    return response.headers.get("Etag"), json_encoder.loads(body.decode("utf-8")), max_age
  File "/usr/local/lib64/python3.8/site-packages/elasticapm/utils/json_encoder.py", line 67, in loads
    return json.loads(value, object_hook=better_decoder)
  File "/usr/lib64/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I'm initializing ElasticAPM as,

``` 
import uvicorn
from fastapi import FastAPI
from elasticapm.contrib.starlette import make_apm_client, ElasticAPM

apm = make_apm_client({
    "SERVICE_NAME": "xxx",
    "SERVER_URL": "xxx,
    "SERVER_TIMEOUT": "xxx",
    "SECRET_TOKEN": "xxx",
    "DEBUG": True
})

app = FastAPI()

app.add_middleware(ElasticAPM, client=apm)
```

Not sure what's causing it but only happens when Uvicorn is starting workers for the first time.

Thanks!

**Comment by beniwohli** [comment]
@JBauto I opened https://github.com/elastic/apm-agent-python/pull/979 to address this. In addition to catching the `JSONDecodeError`, we also log the response we got from APM Server. Would you mind trying to install this in a development/staging environment and checking what the log message says exactly? You can install the code from the PR like so:

    pip install "git+https://github.com/elastic/apm-agent-python.git@refs/pull/979/merge"

**Comment by JBauto** [comment]
Commented [here](https://github.com/elastic/apm-agent-python/pull/979#issuecomment-731294385).
