### ISSUE TITLE
Support for Django instrumentation using ASGI

### ISSUE THREAD

**Issue by HenrikOssipoff** [elastic/apm-agent-python#873]
**Is your feature request related to a problem? Please describe.**
Since Django 3.0 it's been possible to run Django through ASGI. Some benchmarks are showing that running Django using ASGI over WSGI in itself is actually a gain, so it might make sense to support ASGI in this case.
Further more, starting with Django 3.1 (currently in beta), we'll be able to use async views, making it even more attractive.

Currently attempting to instrumenting Django using the normal setup-guide will result in the following exception (it seems like heades in WSGI are functioning as dicts, while they're list of lists in ASGI):

```
Traceback (most recent call last):
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/daphne/cli.py", line 30, in asgi
    await self.app(scope, receive, send)
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/django/asgi.py", line 34, in sentry_patched_asgi_handler
    return await middleware(scope, receive, send)
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/asgi.py", line 106, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/asgi.py", line 143, in _run_app
    raise exc from None
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/asgi.py", line 140, in _run_app
    return await callback()
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/django/core/handlers/asgi.py", line 155, in __call__
    await sync_to_async(signals.request_started.send)(sender=self.__class__, scope=scope)
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/asgiref/sync.py", line 296, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/Users/henrik/.pyenv/versions/3.8.1/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/Users/henrik/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/asgiref/sync.py", line 334, in thread_handler
    return func(*args, **kwargs)
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/elasticapm/contrib/django/apps.py", line 144, in _request_started_handler
    trace_parent = TraceParent.from_headers(kwargs["scope"]["headers"])
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/elasticapm/utils/disttracing.py", line 96, in from_headers
    tracestate = cls.merge_duplicate_headers(headers, tracestate_header_name)
  File "/Users/henrik/Downloads/.venv/lib/python3.8/site-packages/elasticapm/utils/disttracing.py", line 121, in merge_duplicate_headers
    return headers.get(key)
AttributeError: 'list' object has no attribute 'get'
```

**Describe the solution you'd like**
I'm guessing this will require a separate Django instrumentation module in the async category. It'll be a bit hard for newcomers to know what to choose though, since they'll have two options for Django, but I suppose there's no other way?

**Describe alternatives you've considered**
As far as I've seen, there's not "base ASGI instrumentation middleware" - they're all specific for each ASGI framework, so I've been unable to get something running.

**Comment by beniwohli** [comment]
Hey @HenrikOssipoff 

I think the headers issue should be fixed by https://github.com/elastic/apm-agent-python/pull/856. We'll make a release soon.

As for general ASGI support for Django, this may or may not be a relatively large undertaking. I haven't taken a very close look yet, but AFAIK, Django won't rewrite the ORM and other blocking code paths to non-blocking, but instead run those blocking operations on a separate thread. Currently, we are not able to trace operations on different threads, but we might have an easy solution to do so in https://github.com/elastic/apm-agent-python/pull/705. We haven't investigated too much if this is a viable solution or not, though.

**Comment by beniwohli** [comment]
@HenrikOssipoff can you give the newly released 5.8.0 a try to see if it fixes the exception you reported?

**Comment by HenrikOssipoff** [comment]
@beniwohli We're able to use ASGI now to service our Django without any issues - traces looks perfect 😃  Thanks!

**Comment by beniwohli** [comment]
@HenrikOssipoff thanks for checking, that's good news!

I just remembered that @basepi  contributed a PR to asgiref a while ago to improve context handling in the async-to-sync and sync-to-async bridges. Looking at the asgiref commit history, further improvements have been made since. So there's a possibility that it Just Works :tm: 

Are you already using async views in your app?

**Comment by HenrikOssipoff** [comment]
@beniwohli Not yet, but I think I'll take Django 3.1 beta for a spin soon and make some tests, I'll report back!

**Comment by beniwohli** [comment]
Awesome, thanks! I'll close this issue for now. If you find any issues with async views, feel free to open a new issue :)
